apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-for-redis.fullname" . }}
  labels: {{- include "operator-for-redis.labels" . | nindent 4 }}
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: ["db.ibm.com"]
  resources: ["redisclusters", "redisclusters/status"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator-for-redis.fullname" . }}
  labels: {{- include "operator-for-redis.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator-for-redis.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "operator-for-redis.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
